# -*- coding: utf-8 -*-
"""support vector machines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJqnaZr6TXG9FZnyEWCA4-1frD4fOFB0
"""

from sklearn import datasets
iris=datasets.load_iris()
iris

x=iris.data[:,:2]
print(x)
y=iris.target
print(y)

c=1.0
from sklearn.svm import SVC
svm=SVC(kernel='linear',C=c,gamma=0)
svm.fit(x,y)

import numpy as np
x_min, x_max = x[:, 0].min() - 1, x[:, 0].max() + 1
y_min, y_max = x[:, 1].min() - 1, x[:, 1].max() + 1
h = (x_max - x_min) / 100
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))



import matplotlib.pyplot as plt
plt.subplot(1,1,1)
z = svm.predict(np.c_[xx.ravel(), yy.ravel()])
z = z.reshape(xx.shape)
plt.contour(xx, yy, z, cmap='viridis', alpha=0.8)
plt.scatter(x[:, 0], x[:, 1], c=y, cmap='viridis')
plt.xlim(xx.min(), xx.max())
plt.show()